### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dromanchuck** [Siarhei-Douhi/how-strong-are-you#2]
1. levelsBars, levelsHorisontBar, levelsPushup переместить в отдельную папку
2.  
```jsx
 children={
          <>
            <Button text="<" type="array" onClick={navigateBack} />
            <h1 className={style.title}>Программы тренировок</h1>
          </>
        }
```
когда используется children, то лучше писать так
```jsx
<Header>
    <Button text="<" type="array" onClick={navigateBack} />
     <h1 className={style.title}>Программы тренировок</h1>
</Header>
```
3.`uniqueId` эта функция и в названии на первом месте должно быть действие 
Можно поменять на `getUniqueId`.  Во вторых эта функция повторяется, и поэтому можно переместить ее в отдельную папку, на одном уровне с components, назвать можно `helpers`. И в третьих, использовать эту функцию для key только в тех случаях, когда у item нету id

**Comment by Siarhei-Douhi** [comment]
Спасибо, все исправил
